### ISSUE TITLE
Is the project still alive?

### ISSUE THREAD

**Issue by Raj2032** [anp/moxie#287]
Hi, Is the project still alive?

**Comment by anp** [comment]
Hi! I appreciate you asking! I'd say it's at least dormant, as I've been focusing on my day job and broadening my free time pursuits outside of open source. There's a good chance I'll revisit it in the future since I don't see anything filling the niche I hoped for, but that could always change! I'm confident people will be building apps in Rust eventually but haven't had the energy to push on it myself recently :D.
