### ISSUE TITLE
Dom references and mount/unmount handlers

### ISSUE THREAD

**Issue by theduke** [anp/moxie#50]
Moxie is looking very promising.

I often (and concretely for something I'm working on) need something similar to Reacts `useEffect` and dom references to interact with dom nodes like `<video>`, `<audio>`, ...

I assume this is not yet implemented?

Would be highly appreciated.

If you give some pointers on where to start I could maybe find the time to work on this myself.

**Comment by anp** [comment]
Thanks!

Re: DOM references, it should be easy to extend [MemoElement](https://github.com/anp/moxie/pull/49) to allow direct manipulation.

Because moxie-dom's mutations happen during the calls to your code (rather than in a later reconciliation phase) you shouldn't need scheduler support to choose when to run some code post-update.

`Drop` implementations on memoized values behave like a cleanup function passed to `useEffect`. I do something very similar to `useEffect` in order to install event handlers on DOM nodes: https://github.com/anp/moxie/blob/master/dom/src/lib.rs#L112-L121, and the `attr` method does the same while memoizing based on the value of the attribute: https://github.com/anp/moxie/blob/master/dom/src/lib.rs#L90-L101.

Do you have a pseudocode snippet of how you'd write it in React? I can attempt to translate. I also am thinking about how to clean up the implementations I linked above, probably with new memoization semantics for "store this thing for now and don't bother returning anything to the calling code."

**Comment by theduke** [comment]
Here is a snippet:

```javascript
function VideoPlayer() {
  const videoRef = useRef(null);
  const onPlay = () => {
    inputEl.current.play();
  };
  return (
    <div>
      <video ref={videoRef}>...</video>
      <button onClick={onPlay}>Play</button>
    <div>
  );
}
```

ps: very much looking forward to see how the JSX pull request develops. Current code is quite awkward to write.

**Comment by anp** [comment]
I just pushed https://github.com/anp/moxie/pull/52 which I *think* addresses this use case. One key bit here is that we don't need an effect handler to run after reconciliation, because the creation and mutation of the elements happens synchronously as you declare them.

In the current syntax, approximately:

```rust
#[topo::aware]
fn video_player() {
    element!("div", |e| {
        let mut raw_video_element = None;
        element!("video", |e| {
            raw_video_element = Some(e.raw_element_that_has_sharp_edges_please_be_careful());
            // ...
        });

        let video_elem = raw_video_element.unwrap();

        element!("button", |e| {
            e.on(move |_: ClickEvent| video_elem.play());
        });
    });
}
```

Something like this, at least. And yeah, I agree that this is quite awkward to write, to say the least :P.

**Comment by theduke** [comment]
Awkward, but after trying it out yesterday, it works indeed. Thanks.
